### ISSUE TITLE
$line

### ISSUE THREAD

**Issue by johnjohnk2** [rhymeswithmogul/Termbin4PS#1]
it creates a string in begin, then just appends to it in process. It calls the variable $line, but calling a variable $line doesn't magic up end of line characters  ---> that should be fixed in the Out-TermBin command because it makes it quite useless

**Comment by rhymeswithmogul** [comment]
Thank you both!  I've merged the suggested changes.  Could you clone the Git tree and try it out?

**Comment by johnjohnk2** [comment]
Hi,

Thanks to @indented-automation he did all the job ;-)  @rhymeswithmogul  Did you release the module to the PS gallery already ( in order i can test it)? Thanks

**Comment by rhymeswithmogul** [comment]
Sure did!  You'll have to `Install-Module -AllowPrerelease -Force` to get it, though.

**Comment by johnjohnk2** [comment]
Perfect I did an  Install-Module -Name Termbin4PS -AllowPrerelease -Force  ? 

Just another question, why the module is going to C:\User\Documents and not to the PSmodulepath ?

**Comment by johnjohnk2** [comment]
@indented-automation @rhymeswithmogul  It works perfectly 
https://termbin.com/j3hv
with only (tree /F ) | Out-TermBin

**Comment by rhymeswithmogul** [comment]
Awesome! I’ll push 1.1.2 to PSGallery tomorrow. Thank you both!
